### ISSUE TITLE
I want to execute multiple SQL statements

### ISSUE THREAD

**Issue by Carson126** [vielhuber/dbhelper#1]
I want to execute multiple SQL statements，with query get errors，some sql in sql files，any ideas？

**Comment by vielhuber** [comment]
Executing multiple SQL Statements is always tricky, but it should be possible.

Can you post an example of your SQL Statement, that does not work?

**Comment by Carson126** [comment]
T-SQL like these:


DROP TABLE IF EXISTS tablename;
CREATE TABLE IF NOT EXISTS tablename(...
)comment="";

create proc... #for tablename
create trigger ... # for tablename
create view .... # for tablename

insert into tablename (field1,field2) values('...','....');

CREATE TABLE IF NOT EXISTS tablename1(...
)comment="";

select @@identity into @id;
insert into tablename (xid,filed1,field2) values(@id,'...','...');
insert into tablename1 (xid,filed1,field2) values(@id,'...','...');

select * from tablename a1 left join tablename1 b1 on (a.id=b.id) where a.id=@id

**Comment by vielhuber** [comment]
Normally every statement is prepared, preparsed and executed.

Despite that you can use the undocumented, underlying ```exec```-function (if you use PDO).

Just do this for example to execute two statements:
```php
$db->sql->exec('
   INSERT INTO test(col1,col2,col3) VALUES (\'foo\',\'bar\',\'baz\');
   INSERT INTO test(col1,col2,col3) VALUES (\'foo\',\'bar\',\'baz\');
');
```

This should work.

**Comment by Carson126** [comment]
does it include $stam
like $db->sql->exec($mutiSql,$stam)
thanks a lot

**Comment by vielhuber** [comment]
What do you mean by $stam?
