### ISSUE TITLE
is there a way to prevent bit to base64

### ISSUE THREAD

**Issue by Carson126** [vielhuber/dbhelper#2]
is there a way to prevent mysql bit type to base64
i don't want to convert 1 to \u0001

**Comment by vielhuber** [comment]
Can you please expand upon this topic a little more further.
What do you mean by "bit type to base64"?

**Comment by Carson126** [comment]
sorry,  this is unicode not base64

**Comment by Carson126** [comment]
select field(bit) from xxx;
after query and json_encode()
i got field with "\u0000" or "\u0001"

**Comment by vielhuber** [comment]
It seems that you have the wrong db char encoding.

Can you send me a dump of your database at david@vielhuber.de and an example query?

Then I can elaborate a little more on that.
